SELECT processes.f_register_process('Iseseisva töö esitamise ja hindamise protsess', 'Admebaaside II projekt.', 1, NULL);
SELECT processes.f_add_first_parallel_activity(3, 'Ettevalmistus');
SELECT processes.f_add_action_in_parallel_activity(1, 1, 'Registreeri ettenäitamisele');
SELECT processes.f_add_action_in_parallel_activity(1, 1, 'Lae failid Maurusesse');
SELECT processes.f_add_decision_to_step(1, 1, 'Kas saan kohale tuua?');
SELECT processes.f_add_option_to_decision(4, NULL, 'Jah VÕI (ei ja ettenäitamiseni vähem kui 24 tundi)');
SELECT processes.f_add_option_to_decision(4, NULL, 'Ei JA ettenäitamiseni rohkem kui 24 tundi');
SELECT processes.f_add_action_to_option(1, 1, 'Tühista registreerimine');
SELECT processes.f_add_action_to_step_existing_next(1, 11, 4,'Registreeri ettenäitamisele');
SELECT processes.f_add_action_to_option(1, 2, 'Ole kohal (vähemalt üks autor)');
SELECT processes.f_add_parallel_activity_to_step(1, 13, 'Kohtumine');
SELECT processes.f_add_action_in_parallel_activity(1, 14, 'Vaata iseseisev töö koos õppejõuga üle');
SELECT processes.f_add_action_in_parallel_activity(1, 14, 'Tee märkmeid');
SELECT processes.f_add_decision_to_step(1, 14, 'Kuidas iseseisva tööga lood on?');
SELECT processes.f_add_option_to_decision(17, NULL, 'Iseseisvas töös on pisivead JA õppejõud annab loa kohapeal parandamiseks');
SELECT processes.f_add_option_to_decision(17, NULL, 'Iseseisev töö on korras');
SELECT processes.f_add_action_to_option_existing_next(1, 5, 13, 'Paranda kohapeal');
SELECT processes.f_add_action_to_option(1, 6, 'Õppejõud: määra projekti kordaja, mis sõltub arvestuse saamise ajast');
SELECT processes.f_add_decision_table(20, 'Kordajad');
SELECT processes.f_add_decision_table_entry(1, 'Õppenädal, mil arvestati', 'Projekti kordaja', 1::smallint);
SELECT processes.f_add_decision_table_entry(1, '1-13', '1.3', 2::smallint);
SELECT processes.f_add_decision_table_entry(1, '14-15', '1.2', 3::smallint);
SELECT processes.f_add_decision_table_entry(1, '16', '1.1', 4::smallint);
SELECT processes.f_add_decision_table_entry(1, '17-18', '1.0', 5::smallint);
SELECT processes.f_add_decision_table_entry(1, '19-20', '0.9', 6::smallint);
SELECT processes.f_add_action_to_step(1, 20, 'Iseseisev töö on arvestatud');
SELECT processes.f_add_option_to_decision(17, NULL, 'Iseseisvas töös on suured puusused VÜI (iseseisvas töös on pisivead ja õppejõud ei anna kohapeal parandamiseks luba)');
SELECT processes.f_add_parallel_activity_to_option_existing_next(1, 7, 4, 'Parandamine');
SELECT processes.f_add_action_in_parallel_activity(1, 23, 'Registreeri ettenäitamisele');
SELECT processes.f_add_action_in_parallel_activity(1, 23, 'Paranda iseseisvat tööd');
SELECT processes.f_add_action_in_parallel_activity(1, 23, 'Lae failid Maurusesse');
